#version 460 core

#include "volume.glsl"
#include "strand.glsl"

layout(std430, binding = 0) buffer Segments {
    uint segments[];
};

layout(std430, binding = 1) buffer Positions {
    vec3 positions[];
};

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 3, r8) uniform image3D density_volume;

void main() {
    imageStore(density_volume, ivec3(gl_GlobalInvocationID.xyz), vec4(0.0f));
}
