#version 460 core

#include "sample_volume.glsl"
#include "../strand/strand.glsl"
#include "bounding_box.glsl"

layout(std430, binding = 0) buffer Vertices {
    vec3 positions[];
};

layout(local_size_x = 512) in;

layout(binding = 3, r8) uniform image3D density_volume;

void main() {
    vec3 voxel_size = volume_bounds.size / volume_resolution;
    vec3 voxel = (positions[gl_GlobalInvocationID.x] - volume_bounds.origin) / voxel_size;
    imageStore(density_volume, ivec3(voxel), vec4(1.0));
}
